export const UPDATE_POSITION = "UPDATE_POSITION";
export const UPDATE_RESULT = "UPDATE_RESULT";
export const UPDATE_TIMER = "UPDATE_TIMER";
export const UPDATE_PLAYER_TIME = "UPDATE_PLAYER_TIME";
export const UPDATE_OTHER_PLAYER_TIME = "UPDATE_OTHER_PLAYER_TIME";
export const ADD_INCREMENT_TO_PLAYER_TIME = "ADD_INCREMENT_TO_PLAYER_TIME";
export const ADD_INCREMENT_TO_OPPONENT_TIME = "ADD_INCREMENT_TO_OPPONENT_TIME";

export const ENGING_LEVEL = "ENGINE_LEVEL";
export const CHOOSE_TIME = "CH0OSE_TIME";
export const CHOOSE_COLOR = "CHOOSE_COLOR";

export const START_GAME = "START_GAME";
export const RESTART = "RESTART";
export const UNDO = "UNDO";

export const PLAY_COMPUTER = "PLAY_COMPUTER";
